In [3]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.2'

In [11]:
data=pd.Series([3,5,2,6])
data,data.values,data.index

(0    3
 1    5
 2    2
 3    6
 dtype: int64,
 array([3, 5, 2, 6]),
 RangeIndex(start=0, stop=4, step=1))

In [15]:
data[1],data[1:3], data[:-1]

(np.int64(5),
 1    5
 2    2
 dtype: int64,
 0    3
 1    5
 2    2
 dtype: int64)

In [18]:
data=pd.Series([3,5,2,6], index=['messi','ronaldo','ilya','lasha'])
data['messi']

np.int64(3)

In [20]:
xd={'messi':5,'ilya':56,'lasha':45}
data=pd.Series(xd)
data, data['messi']

(messi     5
 ilya     56
 lasha    45
 dtype: int64,
 np.int64(5))

In [21]:
data['messi':'ilya']

messi     5
ilya     56
dtype: int64

In [23]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 1])

3    c
1    b
dtype: object

In [30]:
snatch={'ilya':198,'lasha':225,'nassar':188,'pablo':105}
cleanandjerk={'ilya':262,'lasha':267,'nassar':228,'pablo':120}

a=pd.Series(snatch)
b=pd.Series(cleanandjerk)
marcas=pd.DataFrame({'mejor snatch':snatch, 'mejor envion':cleanandjerk})
marcas, marcas.index, marcas.columns

(        mejor snatch  mejor envion
 ilya             198           262
 lasha            225           267
 nassar           188           228
 pablo            105           120,
 Index(['ilya', 'lasha', 'nassar', 'pablo'], dtype='object'),
 Index(['mejor snatch', 'mejor envion'], dtype='object'))

In [36]:
marcas['mejor snatch']

ilya      198
lasha     225
nassar    188
pablo     105
Name: mejor snatch, dtype: int64

KeyError: 'col0'